allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@oasiscode/easystore@0.2.1'
